apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: frontend-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: shweta0/backend:v1
        ports:
        - containerPort: 4000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_PORT

        
