apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: frontend-namespace
spec:
  selector:
    app: backend
  ports:
  - port: 4000
    targetPort: 4000
    Type: ClusterIP

     
  