apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  namespace: frontend-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/database
  persistentVolumeReclaimPolicy: delete